version: '3.7'

services:
  app:
    image: ghcr.io/buzzingpixel/docker-blue-ocean-demo-php-app
    environment:
      HOSTNAME: docker-blue-ocean-demo-php-app
    networks:
      - default

  db:
    container_name: docker-blue-ocean-demo-php-db
    image: ghcr.io/buzzingpixel/docker-blue-ocean-demo-php-db
    environment:
      HOSTNAME: docker-blue-ocean-demo-php-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: site
      MYSQL_USER: site
      MYSQL_PASSWORD: secret
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      default:
        aliases:
          - docker-blue-ocean-demo-php-db

volumes:
  db-volume:
